[Variables]

Language=English
;------------------------ Main ---------------------------
;---------------------------------------------------------

Format=H
Hidden=0
Hidden2=1
Player=Winamp
Location=SPXX0050
Unit=c
ScrollMouseIncrement=0.05
Font1=Segoe Script
Font2=Comic Sans MS

UnitOfMeasure=m
FontColor=255,255,255

;------------------- Crytocurrency -------------------------
;-----------------------------------------------------------

[Variables]
Version=1.0.0
BackgroundWidth=361
BottomBarHeight=4
BackgroundColor=24,24,24,217
;BackgroundColor=0,0,0
BorderColor=100,100,100,100
Transparent=0,0,0,1
SolidWhite=255,255,255,255
SolidOffWhite=242,242,242,255
TransparentWhite1=255,255,255,120
TransparentWhite2=255,255,255,90
TransparentWhite3=255,255,255,35
SolidBlack=0,0,0,255
TransparentBlack1=0,0,0,120
TransparentBlack2=0,0,0,90
TransparentBlack3=0,0,0,35
SolidRed=255,0,0
BrightRed=255,51,51
SolidCloseRed=232,17,35
SolidCloseRedHover=241,112,122
SolidGreyText=178,178,178,255
SolidGreyIcon=106,106,106,255
SolidGreyPause=121,121,121,255
BrightGreen=41,163,41
SolidGreen=00cc00
SpotifyGreen=30,215,96
SpotifyBackground=40,40,40
SpotifyForeground=64,64,64
VolumeOverlay=205,205,205,65
HDOverlay=0,0,0,240
IconColorActive= #SolidWhite#
IconColorInactive=#SolidGreyIcon#
MonkeyGold=210,171,86
BitcoinGold=255,153,0
EthereumBlue=128,128,255
CPUBlue=79,155,219
MemoryPurple=139,18,174
DiskGreen=199,216,12
NetworkOrangeDark=167,79,1
NetworkOrangeDarkText=214,101,2
NetworkOrangeLight=237,165,130
YouTubeRed=255,33,100
GooglePlusRed=219,68,55
PinterestRed=189,8,28
FacebookBlue=59,91,153
TwitterBlue=29,161,242
GithubPurple=104,42,129
DonatePurple=219,75,149
SubscribeGreen=96,195,29
USDGreen=0,204,68
CMCRank=204,204,179
CopperNode=184, 115, 51
SilverNode=230,232,250
GoldNode=255,153,0
PlatinumNode=230, 230, 230
DiamondNode=255,255,255,255
24HRed=255,68,55
24HGreen=68,255,55


;----------------------Dock Settings--------------------------
;-------------------------------------------------------------


Icon1NameAndPath=#@#\My Computer.png
Icon1Text=My Computer
LocationPath1=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]

Icon2NameAndPath=#@#\My Documents.png
Icon2Text=My Documents
LocationPath2=[Shell:::{A8CDFF1C-4878-43be-B5FD-F8091C1C60D0}]

Icon3NameAndPath=#@#\Videos.png
Icon3Text=Video
LocationPath3=[Shell:::{A0953C92-50DC-43bf-BE83-3742FED03C9C}]

Icon4NameAndPath=#@#\Pictures.png
Icon4Text=Pictures
LocationPath4=[Shell:::{3ADD1653-EB32-4cb0-BBD7-DFA0ABB5ACCA}]

Icon5NameAndPath=#@#\Music.png
Icon5Text=Music
LocationPath5=[Shell:::{1CF1260C-4DD0-4ebb-811F-33C572699FDE}]

Icon6NameAndPath=#@#\Downloads.png
Icon6Text=Downloads
LocationPath6=[Shell:::{374DE290-123F-4565-9164-39C4925E467B}]

Icon7NameAndPath=#@#\Google.png
Icon7Text=Google
LocationPath7=["https://google.com"]

Icon8NameAndPath=#@#\Facebook.png
Icon8Text=Facebook
LocationPath8=["https://web.facebook.com/"]

Icon9NameAndPath=#@#\Gmail.png
Icon9Text=Gmail
LocationPath9=["https://mail.google.com/mail/"]

Icon10NameAndPath=#@#\Deviantart.png
Icon10Text=Deviantart
LocationPath10=["https://www.deviantart.com/browse/all/customization/skins/sysmonitor/rainmeter/?order=5"]

Icon11NameAndPath=#@#\YouTube.png
Icon11Text=YouTube
LocationPath11=["https://www.youtube.com/"]

Icon12NameAndPath=#@#\Soundcloud.png
Icon12Text=Whatsapp Web
LocationPath12=["https://web.whatsapp.com/"]

Icon13NameAndPath=#@#\Tweeter.png
Icon13Text=Tweeter
LocationPath13=["https://twitter.com/"]

Icon14NameAndPath=#@#\Instagram.png
Icon14Text=Instagram
LocationPath14=["https://www.instagram.com"]

Icon15NameAndPath=#@#\Pinterest.png
Icon15Text=Pinterest
LocationPath15=["https://www.pinterest.com/"]

Icon16NameAndPath=#@#\Reddit.png
Icon16Text=Reddit
LocationPath16=["https://www.reddit.com/"]
